resolver: lts-12.11

packages:
- location: .
- location:
    git: git@github.com:interosinc/dispenser-core.git
    commit: c8a0a9d9b3e2e7251599df8678c08afc667d6cfd
  extra-dep: true

extra-deps:
- monad-io-adapter-0.1.0.0
- protolude-0.2.2
