resolver: lts-12.11

packages:
- location: .
- location:
    git: git@github.com:interosinc/dispenser-core.git
    commit: 6fe85379b1bb5fec6cf64488e1bf1183bec393bc
  extra-dep: true
- location: ../dispenser-tests
  extra-dep: true

extra-deps:
- monad-io-adapter-0.1.0.0@sha256:54b74abb735faf7ab2001befe47ab25ca9cec0e74c856cb44fea44ef326ad517
